/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Data.*;
import Entidades.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author plopez
 */
public class DatosCuartelView extends javax.swing.JInternalFrame {

    CuartelData cd = new CuartelData();
    
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable (int f, int c){
            return false;
        }
    };
    
    public DatosCuartelView() {
        initComponents();
        armarCabecera();
        cargarCuarteles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtDireccion = new javax.swing.JTextField();
        jtCoordX = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jtCoordY = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCuartel = new javax.swing.JTable();
        jbEditar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jbEliminar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Datos del Cuartel");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Datos del Cuartel");

        jLabel2.setText("Nombre del Cuartel:");

        jLabel3.setText("Direccion:");

        jLabel4.setText("Coordenada Y:");

        jLabel5.setText("Coordenada X:");

        jLabel6.setText("Telefono:");

        jLabel7.setText("Correo:");

        jTableCuartel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableCuartel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCuartelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCuartel);

        jbEditar.setText("Editar");
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbNuevo.setText("Guardar");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel8.setText("Codigo Cuartel:");

        jtCodigo.setEditable(false);

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbEditar)
                        .addGap(43, 43, 43)
                        .addComponent(jbNuevo)
                        .addGap(46, 46, 46)
                        .addComponent(jbEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 14, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCoordX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtCoordY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbEditar)
                    .addComponent(jbNuevo)
                    .addComponent(jbLimpiar)
                    .addComponent(jbSalir)
                    .addComponent(jbEliminar))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    
    //Despues de guardar el cuartel actualiza el jTable y vacia los TextField
    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        Cuartel cuartel = new Cuartel();
        if (camposVacios()){
                JOptionPane.showMessageDialog(this,"Debes completar todos los campos");
            }else{
            try{
                cuartel.setNombre_cuartel(jtNombre.getText());
                cuartel.setDireccion(jtDireccion.getText());
                cuartel.setCoord_X(Integer.parseInt(jtCoordX.getText()));
                cuartel.setCoord_Y(Integer.parseInt(jtCoordY.getText()));
                cuartel.setTelefono(jtTelefono.getText());
                cuartel.setCorreo(jtCorreo.getText());
                cuartel.setEstado(true);
            
                cd.crearCuartel(cuartel);
                cargarCuarteles();
                vaciarCampos();
                          
           
            }catch(NumberFormatException n){
                JOptionPane.showMessageDialog(this,"Error en el ingreso de datos");
            
            }
        }
    
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        vaciarCampos();
    }//GEN-LAST:event_jbLimpiarActionPerformed

    
    
    //Despues de actualizar el cuartel actualiza el jTable y vacia los TextField
    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (!(jtCodigo.getText().isEmpty())){
            Cuartel c =new Cuartel();
            if (camposVacios()){
                JOptionPane.showMessageDialog(this,"Debes completar todos los campos");
            }else{
            
                c.setCodCuartel(Integer.parseInt(jtCodigo.getText()));
                c.setNombre_cuartel(jtNombre.getText());
                c.setDireccion(jtDireccion.getText());
                c.setCoord_X(Integer.parseInt(jtCoordX.getText()));
                c.setCoord_Y(Integer.parseInt(jtCoordY.getText()));
                c.setTelefono(jtTelefono.getText());
                c.setCorreo(jtCorreo.getText());
                c.setEstado(true);
                cd.actualizarCuartel(c);
                cargarCuarteles();
                vaciarCampos();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cuartel primero para poder guardar la modificacion");
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    //Al eliminar cuarteles no hay control de excepciones porque el codigo lo saca de jtCodigo
    //que es un textField que no es editable (siempre tiene un entero)
    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        if (!(jtCodigo.getText().isEmpty())){
            cd.eliminarCuartel(Integer.parseInt(jtCodigo.getText()));
            cargarCuarteles();
            vaciarCampos();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un cuartel primero, antes de eliminar");
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    
    //la seleccion del cuartel se realiza con un doble clic
    private void jTableCuartelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCuartelMouseClicked
        if(evt.getClickCount()==2){
         Cuartel cuartel = new Cuartel();
         int codigo = Integer.parseInt(String.valueOf(jTableCuartel.getValueAt(jTableCuartel.getSelectedRow(), 0)));
            cuartel = cd.buscarCuartel(codigo);
            jtCodigo.setText(String.valueOf(codigo));
            jtNombre.setText(cuartel.getNombre_cuartel());
            jtDireccion.setText(cuartel.getDireccion());
            jtCoordX.setText(String.valueOf( cuartel.getCoord_X()));
            jtCoordY.setText(String.valueOf( cuartel.getCoord_Y()));
            jtTelefono.setText(cuartel.getTelefono());
            jtCorreo.setText(cuartel.getCorreo());
       }
    }//GEN-LAST:event_jTableCuartelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCuartel;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtCoordX;
    private javax.swing.JTextField jtCoordY;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtDireccion;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    // End of variables declaration//GEN-END:variables


    private void armarCabecera(){
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");
        jTableCuartel.setModel(modelo);
    }

    private void cargarCuarteles(){
        modelo.setRowCount(0);
        List<Cuartel> cuarteles = new ArrayList();
        cuarteles = cd.listarCuarteles();
        for(Cuartel c : cuarteles){
             modelo.addRow(new Object[]{c.getCodCuartel(),c.getNombre_cuartel(),c.getDireccion(),c.getTelefono()});
        }
    }
    
    private boolean camposVacios(){
        return (jtNombre.getText().isEmpty() || jtDireccion.getText().isEmpty() || jtCoordX.getText().isEmpty() || jtCoordY.getText().isEmpty() || jtTelefono.getText().isEmpty() || jtCorreo.getText().isEmpty());
    }
    
    
    private void vaciarCampos(){
        jtCodigo.setText("");
        jtNombre.setText("");
        jtDireccion.setText("");
        jtCoordX.setText("");
        jtCoordY.setText("");
        jtTelefono.setText("");
        jtCorreo.setText("");
    }

}
