/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import Data.*;
import Entidades.*;
import java.time.ZoneId;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pablo
 */
public class ResolSiniestroView extends javax.swing.JInternalFrame {

    SiniestroData sd = new SiniestroData();
    BrigadaData bd = new BrigadaData();

    private DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int f, int c) {
            return false;
        }
    };

    public ResolSiniestroView() {
        initComponents();
        armarCabecera();
        cargarSiniestros();
        jcBoxPuntos.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableSiniestro = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcResolucion = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jcBoxPuntos = new javax.swing.JComboBox<>();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        setClosable(true);
        setTitle("Resolucion de Siniestro");

        jTableSiniestro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableSiniestro);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Resolucion de Siniestros");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Siniestros");

        jLabel3.setText("Fecha de Resolucion:");

        jLabel4.setText("Puntuacion:");

        jcBoxPuntos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(353, 353, 353)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(425, 425, 425)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(jcResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jcBoxPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jbGuardar)
                                .addGap(63, 63, 63)
                                .addComponent(jbSalir))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcBoxPuntos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jbGuardar)
                        .addComponent(jbSalir))
                    .addComponent(jcResolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        LocalDate fechaSiniestro = null;
        if (camposVacios()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un siniestro, luego una fecha de resolución y una puntuación del siniestro");
        } else {
            try {
                Siniestro siniestro = new Siniestro();
                siniestro.setCodigo(Integer.parseInt(String.valueOf(jTableSiniestro.getValueAt(jTableSiniestro.getSelectedRow(), 0))));
                // Procesar fecha de siniestro
                String fechaSiniestroString = String.valueOf(jTableSiniestro.getValueAt(jTableSiniestro.getSelectedRow(), 1));
                DateTimeFormatter formatterSiniestro = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                System.out.println("Fecha a analizar: " + fechaSiniestroString);
                //LocalDateTime fechaSiniestroDateTime = LocalDateTime.parse(fechaSiniestroString, formatterSiniestro);
                fechaSiniestro = LocalDate.parse(fechaSiniestroString, formatterSiniestro);
                siniestro.setFecha_siniestro(fechaSiniestro.atStartOfDay());

                LocalDate fechaResolucion = jcResolucion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

                LocalDateTime fechaResolucionDateTime = fechaResolucion.atStartOfDay();
                siniestro.setFecha_resol(fechaResolucion.atStartOfDay());
                System.out.println("Fecha de resolución a analizar: " + jcResolucion.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
                // Otros atributos
                siniestro.setTipo(String.valueOf(jTableSiniestro.getValueAt(jTableSiniestro.getSelectedRow(), 2)));
                siniestro.setCodBrigada(bd.buscarBrigada(Integer.parseInt(String.valueOf(jTableSiniestro.getValueAt(jTableSiniestro.getSelectedRow(), 3)))));
                siniestro.setDetalle(String.valueOf(jTableSiniestro.getValueAt(jTableSiniestro.getSelectedRow(), 5)));
                siniestro.setPuntuacion(Integer.parseInt(jcBoxPuntos.getSelectedItem().toString()));

                // Después de parsear las fechas
                if (fechaResolucion.isBefore(fechaSiniestro)) {
                    JOptionPane.showMessageDialog(this, "La fecha de resolución debe ser posterior a la fecha de siniestro");
                } else {
                    // El código existente para guardar el siniestro si la validación es exitosa
                    sd.completarSiniestro(siniestro);
                    cargarSiniestros();
                }
            } catch (DateTimeParseException | NumberFormatException ex) {
                String mensajeError = "Error en el formato de fecha u hora. Asegúrate de seleccionar valores válidos.\n"
                        + "Mensaje de error: " + ex.getMessage() + "\n"
                        + "Línea donde ocurrió el error: " + ex.getStackTrace()[0].getLineNumber();

                JOptionPane.showMessageDialog(this, mensajeError, "Error", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace(); // Opcional: Imprimir la traza de la excepción para depuración
            }
        }


    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableSiniestro;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<String> jcBoxPuntos;
    private com.toedter.calendar.JDateChooser jcResolucion;
    // End of variables declaration//GEN-END:variables

    private void armarCabecera() {
        modelo.addColumn("ID");
        modelo.addColumn("Fecha");
        modelo.addColumn("Tipo");
        modelo.addColumn("ID Brigada");
        modelo.addColumn("Brigada");
        modelo.addColumn("Detalles");
        jTableSiniestro.setModel(modelo);

    }

    private void cargarSiniestros() {
        modelo.setRowCount(0);
        List<Siniestro> siniestros = new ArrayList();
        siniestros = sd.listarSiniestrosNOResueltos();
        for (Siniestro s : siniestros) {
            modelo.addRow(new Object[]{s.getCodigo(), s.getFecha_siniestro().toLocalDate(), s.getTipo(), s.getCodBrigada().getCodBrigada(), s.getCodBrigada().getNombre_br(), s.getDetalle()});
        }
    }

    private boolean camposVacios() {
        return (jcBoxPuntos.getSelectedIndex() == -1 || (jcResolucion.getDate() == null) || jTableSiniestro.getSelectedRow() == -1);
    }
}
