/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Data.SiniestroData;
import Entidades.Siniestro;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class SiniestroView extends javax.swing.JInternalFrame {

    private Siniestro siniestroActual = null;
    private SiniestroData siniestro = null;

    /**
     * Creates new form SiniestroView
     */
    public SiniestroView() {
        initComponents();
        siniestroActual = new Siniestro();
        siniestro = new SiniestroData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        calendario = new com.toedter.calendar.JDateChooser();
        JtHora = new javax.swing.JFormattedTextField();
        jTextDetalle = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBLimpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBGuardar = new javax.swing.JButton();
        jTextX = new javax.swing.JTextField();
        jTextY = new javax.swing.JTextField();

        setClosable(true);

        jLabel1.setText("jLabel1");

        jLabel2.setText("Detalle");

        jLabel3.setText("Hora del siniestro");

        jLabel4.setText("Tipo");

        jLabel5.setText("Coordenada Y");

        jLabel6.setText("Coordenada X");

        jLabel7.setText("Fecha del siniestro");

        try {
            JtHora.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incendios en viviendas e industrias", "Salvamento en derrumbes", "Rescates en ámbito montaña", "Rescate de personas atrapadas en accidentes de tráfico", "Socorrer inundaciones", "Operativos de prevención." }));

        jBLimpiar.setText("Limpiar");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        jButton2.setText("Validar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBGuardar.setText("Guardar");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(162, 162, 162)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(369, 369, 369)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                            .addGap(2, 2, 2)
                                                            .addComponent(JtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGap(18, 18, 18)
                                                            .addComponent(jButton2))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jBGuardar)
                                                            .addGap(127, 127, 127)
                                                            .addComponent(jBLimpiar)))
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 30, Short.MAX_VALUE)))))
                                .addGap(144, 144, 144)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(13, 13, 13)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBLimpiar)
                    .addComponent(jBGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        // Obtener el tipo del JComboBox
        String tipo = (String) jComboBox1.getSelectedItem();
        if (tipo == null || tipo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Debe seleccionar un tipo de siniestro.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }
        siniestroActual.setTipo(tipo);

        // Obtener la fecha del JDateChooser
        java.util.Date fechaSeleccionada = calendario.getDate();
        if (fechaSeleccionada == null) {
            JOptionPane.showMessageDialog(this, "Error: Debe seleccionar una fecha.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }
        Instant instant = fechaSeleccionada.toInstant();
        LocalDate fechaSiniestro = instant.atZone(ZoneId.systemDefault()).toLocalDate();

        // Obtener la hora del JFormattedTextField
        String horaString = JtHora.getText().trim();
        if (horaString.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar una hora.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }

        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm");
        try {
            LocalTime horaSiniestro = LocalTime.parse(horaString, formatter);
            siniestroActual.setFecha_siniestro(LocalDateTime.of(fechaSiniestro, horaSiniestro));
        } catch (DateTimeParseException e) {
            JOptionPane.showMessageDialog(this, "Error: Formato de hora incorrecto. Debe ingresar la hora en formato HH:mm.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }

        // Corregir el manejo de las coordenadas
        try {
            int coordX = Integer.parseInt(jTextX.getText());
            int coordY = Integer.parseInt(jTextY.getText());
            siniestroActual.setCoord_X(coordX);
            siniestroActual.setCoord_Y(coordY);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Ingrese valores numéricos válidos para las coordenadas.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }

        // Verificar que se haya ingresado un detalle
        String detalle = jTextDetalle.getText();
        if (detalle.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Error: Debe ingresar el detalle del siniestro.", "Error", JOptionPane.ERROR_MESSAGE);
            return; // Salir del método
        }
        siniestroActual.setDetalle(detalle);

        // Intenta insertar el nuevo Siniestro
        siniestro.crearSiniestro(siniestroActual);


    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        // Limpiar campos
        jTextDetalle.setText("");
        jTextX.setText("");
        jTextY.setText("");
        JtHora.setText("");
        calendario.setDate(null); // Establecer la fecha en null para limpiar el JDateChooser
        jComboBox1.setSelectedIndex(0); // Establecer el índice seleccionado en 0 (o cualquier valor predeterminado que desees)

        // Otros campos específicos que puedas tener en tu interfaz de usuario
        // También puedes reiniciar el objeto siniestroActual si es necesario
        siniestroActual = new Siniestro();
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         if (ValidarHora(JtHora.getText()) == true) {
            JOptionPane.showMessageDialog(this, "Hora correcta");
        } else {
            JOptionPane.showMessageDialog(this, "Hora incorrecta");

        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public boolean ValidarHora(String Hora) {
        boolean b;
        char[] a = Hora.toString().toCharArray();
        String[] c = Hora.split(":");
        if ((a[0] == ' ') || (a[1] == ' ') || (a[2] == ' ') || (a[3] == ' ') || (a[4] == ' ') || (getInteger(c[0]) > 24) || (getInteger(c[1]) > 59)) {
            b = false;
        } else {
            b = true;
        }
        return b;
    }

    public int getInteger(String valor) {
        int integer = Integer.parseInt(valor);
        return integer;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField JtHora;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextDetalle;
    private javax.swing.JTextField jTextX;
    private javax.swing.JTextField jTextY;
    // End of variables declaration//GEN-END:variables
}
